version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15  # 指定包含pgvector扩展的版本
    container_name: postgres_db
    environment:
      POSTGRES_USER: lianpu
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai       # 设置时区
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:             # 健康检查
      test: ["CMD", "pg_isready", "-U", "lianpu"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "max_connections=200"]  # 自定义配置

volumes:
  pgdata: